INSERT INTO
  users (username, email, bio, age, ROLE)
VALUES
  ('user1', 'user1@example.com', 'Software engineer with 5 years of experience in web development.', 28, 'Admin'),
  ('user2', 'user2@example.com', 'Product manager specializing in SaaS applications.', 34, 'User'),
  ('user3', 'user3@example.com', 'Digital marketing specialist focused on growth hacking.', 26, 'User'),
  ('user4', 'user4@example.com', 'Data analyst with expertise in Python and R.', 31, 'Moderator'),
  ('user5', 'user5@example.com', 'UX designer passionate about creating intuitive interfaces.', 29, 'Moderator'),
  ('user6', 'user6@example.com', 'Full-stack developer with Node.js and React experience.', 27, 'Moderator'),
  ('user7', 'user7@example.com', 'Project coordinator with agile methodology background.', 33, 'User'),
  ('user8', 'user8@example.com', 'QA engineer specializing in automated testing.', 30, 'Moderator'),
  ('user9', 'user9@example.com', 'DevOps engineer with expertise in CI/CD pipelines.', 35, 'Moderator'),
  ('user10', 'user10@example.com', 'Content writer focused on technical documentation.', 28, 'User'),
  ('user11', 'user11@example.com', 'Business analyst with financial sector experience.', 36, 'Moderator'),
  ('user12', 'user12@example.com', 'Mobile app developer specializing in Flutter.', 25, 'Moderator'),
  ('user13', 'user13@example.com', 'System administrator with cloud infrastructure expertise.', 32, 'Admin'),
  ('user14', 'user14@example.com', 'Frontend developer skilled in modern JavaScript frameworks.', 27, 'Moderator'),
  ('user15', 'user15@example.com', 'Database administrator with PostgreSQL specialization.', 40, 'Admin'),
  ('user16', 'user16@example.com', 'SEO specialist with content optimization skills.', 29, 'User'),
  ('user17', 'user17@example.com', 'Backend developer with Java and Spring Boot experience.', 31, 'Moderator'),
  ('user18', 'user18@example.com', 'Network engineer specialized in security protocols.', 34, 'Admin'),
  ('user19', 'user19@example.com', 'Customer support specialist with technical background.', 26, 'User'),
  ('user20', 'user20@example.com', 'Machine learning engineer focused on NLP.', 33, 'Moderator'),
  ('user21', 'user21@example.com', 'Technical writer with API documentation expertise.', 28, 'User'),
  ('user22', 'user22@example.com', 'UI designer with accessibility specialization.', 30, 'Moderator'),
  ('user23', 'user23@example.com', 'Game developer with Unity experience.', 27, 'Moderator'),
  ('user24', 'user24@example.com', 'Scrum master certified in agile methodologies.', 32, 'User'),
  ('user25', 'user25@example.com', 'Information security analyst with CISSP certification.', 36, 'Admin'),
  ('user26', 'user26@example.com', 'Cloud architect specialized in AWS services.', 38, 'Moderator'),
  ('user27', 'user27@example.com', 'E-commerce specialist with conversion optimization skills.', 29, 'User'),
  ('user28', 'user28@example.com', 'Mobile QA tester with automation expertise.', 26, 'Moderator'),
  ('user29', 'user29@example.com', 'Technical product manager with engineering background.', 34, 'User'),
  ('user30', 'user30@example.com', 'Blockchain developer focused on smart contracts.', 30, 'Moderator');