[package]
authors = []
description = ""
edition = "2021"
license = ""
name = "maestro-serpapi"
repository = ""


[dependencies]
bon = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
