[package]
authors = { workspace = true }
description = "Shadcn-style pre-theming for Dioxus"
edition = { workspace = true }
license = { workspace = true }
name = "maestro-themes"
repository = { workspace = true }

[dependencies]
async-std = "1.13.1"
dioxus = { version = "0.6.3" }
dioxus-desktop = { version = "0.6.3", optional = true }
dioxus-free-icons = { version = "0.9.0", features = ["bootstrap", "feather", "font-awesome-solid", "ionicons", "lucide"] }
directories = { version = "6.0.0", optional = true }
maestro-hooks = { path = "../maestro-hooks" }
maestro-ui = { path = "../maestro-ui" }
serde = "1.0.219"
strum = "^0.27.1"
strum_macros = "^0.27.1"
syntect = { version = "5.2.0", default-features = false, features = ["default-fancy"] }
tailwind_fuse = { version = "0.3.2", features = ["variant"] }
wasm-bindgen = { version = "0.2.100", optional = true }
web-sys = { version = "0.3.77", features = [
  "DomTokenList",
  "Element",
  "MediaQueryList",
  "MediaQueryListEvent",
  "Storage",
  "Window",
  "console",
], optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", features = [
  "Data_Xml_Dom",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_UI_Controls",
  "Win32_UI_WindowsAndMessaging",
], optional = true }
winreg = { version = "0.55.0", optional = true }

[target.'cfg(macos)'.dependencies]
cocoa = { version = "0.26.0", optional = true }
core-foundation = { version = "0.10.0", optional = true }
objc = { version = "0.2.7", optional = true }

[target.'cfg(linux)'.dependencies]


[build-dependencies]
dotenvy = { git = "https://github.com/allan2/dotenvy.git", features = ["macros"] }

[features]
desktop = ["dep:dioxus-desktop", "dep:directories", "dioxus/desktop"]
macos = ["cocoa", "core-foundation", "objc"]
web = ["dep:wasm-bindgen", "dep:web-sys", "dioxus/web"]
windows = ["dep:windows", "winreg"]
