[package]
authors = { workspace = true }
description = "Shadcn-style pre-theming for Dioxus"
edition = { workspace = true }
license = { workspace = true }
name = "maestro-themes"
repository = { workspace = true }

[dependencies]
cocoa = { version = "0.26.0", optional = true }
core-foundation = { version = "0.10.0", optional = true }
dioxus = { workspace = true }
dioxus-desktop = { version = "0.6.3", optional = true }
directories = { version = "6.0.0", optional = true }
objc = { version = "0.2.7", optional = true }
wasm-bindgen = { version = "0.2.100", optional = true }
web-sys = { version = "0.3.77", features = [
  "DomTokenList",
  "Element",
  "MediaQueryList",
  "MediaQueryListEvent",
  "Storage",
  "Window",
  "console",
], optional = true }
windows = { version = "0.61.1", features = [
  "Data_Xml_Dom",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_UI_Controls",
  "Win32_UI_WindowsAndMessaging",
], optional = true }
winreg = { version = "0.55.0", optional = true }


[features]
desktop = ["dep:directories", "dioxus-desktop", "dioxus/desktop", "linux", "macos", "windows"]
linux = []
macos = ["dep:cocoa", "dep:core-foundation", "dep:objc"]
mobile = []
web = ["dep:wasm-bindgen", "dep:web-sys", "dioxus/web"]
windows = ["dep:windows", "dep:winreg"]
