[package]
authors = []
description = ""
edition = "2021"
license = ""
name = "maestro-sqlx"
repository = ""


[dependencies]
serde = { workspace = true }

sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"], optional = true }
tokio = { version = "1.43.0", features = ["full"], optional = true }

[features]
acreate = ["dep:sqlx"]
create = ["acreate", "dep:tokio"]
