[package]
name = "demo"
version = "0.1.0"
authors = ["bigs <oketchs702@gmail.com>"]
edition = "2021"

[dependencies]
# local deps

# clients
maestro-diesel = { path = "../clients/maestro-diesel", features = ["async", "sync", "server"] }
maestro-sqlx = { path = "../clients/maestro-sqlx", features = ["acreate", "create"] }

# components and utilities
maestro-toast = { path = "../frontend/maestro-toast" }
maestro-hooks = { path = "../frontend/maestro-hooks" }
maestro-forms = { path = "../frontend/maestro-forms" }
maestro-plotters = { path = "../frontend/maestro-plotters" }
maestro-query = { path = "../frontend/maestro-query" }
maestro-radio = { path = "../frontend/maestro-radio" }
maestro-ui = { path = "../frontend/maestro-ui" }


# thrird party deps
dioxus = { version = "0.6.1", features = ["fullstack", "router"] }
dioxus-web = "0.6.1"
dioxus-router = "0.6.1"
log = "0.4"
wasm-logger = "0.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
validator = { version = "0.19.0", features = ["derive"] }
apalis = { version = "0.5.5", features = ["cron", "postgres"], optional = true }
apalis-core = "0.5.5"
dioxus-ssr = "0.6.1"
async-std = "1.13.0"
web-sys = "0.3.76"
plotters = "0.3.7"
chrono = "0.4.39"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop", "apalis"]
mobile = ["dioxus/mobile", "apalis"]
