[package]
name = "demo"
version = "0.1.0"
authors = ["bigs <oketchs702@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { workspace = true }
dioxus-web = "0.6.1"
dioxus-router = "0.6.1"
log = "0.4"
wasm-logger = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
validator = { workspace = true }

# local deps
maestro-forms = { workspace = true }
maestro-sqlx = { workspace = true, features = ["apalis-async", "apalis-sync"]}
maestro-toast = { workspace = true }
apalis = { version = "0.5.5", features = ["cron", "postgres"], optional = true }
apalis-core = "= 0.5.5"
dioxus-ssr = "0.6.1"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop", "apalis"]
mobile = ["dioxus/mobile", "apalis"]
