[package]
authors = ["Stephen <oketchs702@gmail.com>"]
edition = "2021"
name = "demo"
version = "0.1.0"

[dependencies]
# local deps

# clients
maestro-diesel = { path = "../clients/maestro-diesel", features = ["async", "server", "sync"], optional = true }
maestro-sqlx = { path = "../clients/maestro-sqlx", features = ["acreate", "create"], optional = true }

# components and utilities
maestro-forms = { path = "../frontend/maestro-forms" }
maestro-hooks = { path = "../frontend/maestro-hooks" }
maestro-plotters = { path = "../frontend/maestro-plotters" }
maestro-query = { path = "../frontend/maestro-query" }
maestro-radio = { path = "../frontend/maestro-radio" }
maestro-toast = { path = "../frontend/maestro-toast", features = ["web"]}
maestro-ui = { path = "../frontend/maestro-ui" }


# thrird party deps
dioxus = { version = "0.6.1", features = ["fullstack", "router"] }
apalis = { version = "0.5.5", features = ["cron", "postgres"], optional = true }
apalis-core = { version = "0.5.5", optional = true }
log = "0.4"
serde = { version = "1.0.217", features = ["derive"] }
strum = "0.26.3"
strum_macros = "0.26.4"
validator = { version = "0.19", features = ["derive"] }
serde_json = "1.0.134"
dioxus-logger = "0.6.2"
async-std = "1.13.0"
chrono = { workspace = true }
instant = { version = "0.1.13", features = ["wasm-bindgen"] }
js-sys = "0.3.77"
tailwind_fuse = { version = "0.3.1", features = ["variant"] }
plotters = { version = "0.3.7", default-features = false, features = [
  "all_elements",
  "all_series",
  "bitmap_backend",
  "bitmap_encoder",
  "bitmap_gif",
  "chrono",
  "colormaps",
  "deprecated_items",
  "full_palette",
  "image",
  "svg_backend",
] }
web-sys = "0.3.76"
dioxus-free-icons.workspace = true

[build-dependencies]
dotenvy = { git = "https://github.com/allan2/dotenvy.git", features = ["macros"] }

[features]
default = ["web"]
desktop = ["apalis", "dioxus/desktop"]
mobile = ["apalis", "dioxus/mobile"]
server = ["dep:apalis-core", "dep:maestro-diesel", "dep:maestro-sqlx", "dioxus/server"]
web = ["dioxus/web"]
