[package]
authors = []
description = ""
edition = "2021"
license = ""
name = "maestro-serpapi"
repository = ""


[dependencies]
bon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

reqwest = { version = "0.12.12", features = ["json", "multipart"], optional = true }

dioxus = { version = "0.6.1", features = ["fullstack"], optional = true }

[features]
dioxus = ["Dep:dioxus"]
server = ["dep:reqwest", "dioxus?/server"]
